### ISSUE TITLE
Images result

### ISSUE THREAD

**Issue by SimonLab** [akitten/public-profile-page-url-finder#12]
When the result of search contains some images, the application is not able to get the link: [L26](https://github.com/akitten/public-profile-page-url-finder/blob/40b41d9fd1c454ab5f2b8efeb04c3b98bfcd67d9/lib/finder.js#L26)

**Comment by nelsonic** [comment]
@SimonLab were you able to get an *example* of when this occurs?

**Comment by SimonLab** [comment]
@nelsonic [this search for example](https://www.google.co.uk/search?q=Alex%20Bubb%20Microsoft)

**Comment by nelsonic** [comment]
closing as this was fixed in #15
