### ISSUE TITLE
Problem with shop on Google 

### ISSUE THREAD

**Issue by heron2014** [akitten/public-profile-page-url-finder#16]
![googleshop](https://cloud.githubusercontent.com/assets/8476884/10638425/cc0c6eac-7802-11e5-968a-1545c42e5279.png)
![shop](https://cloud.githubusercontent.com/assets/8476884/10638447/de56663a-7802-11e5-8a45-d1f93f640d16.png)
Attempt to access href tag on span [L24](https://github.com/akitten/public-profile-page-url-finder/blob/d44e5dd32e579153b9cfbd537d65cc71525fd99e/lib/finder.js#L24)

**Comment by nelsonic** [comment]
Makes sense. please add a `test` for this and an `if` condition for pages that have shopping items.

**Comment by nelsonic** [comment]
closed by PR #17
