### ISSUE TITLE
Status code of the response

### ISSUE THREAD

**Issue by SimonLab** [akitten/public-profile-page-url-finder#20]
Check if the status code of the [response](https://github.com/akitten/public-profile-page-url-finder/blob/77e1462a134f0895758dcd0c32e14e0d3a3c5782/lib/searcher.js#L36) is 200. If not, should the program return an error.

It is useful for example if you are doing too many requests to Google. In this case Google will respond with a 302 status code.

**Comment by nelsonic** [comment]
Agreed. good idea. are you implementing?

**Comment by SimonLab** [comment]
yes I'm going to work on it.

**Comment by nelsonic** [comment]
Nice one. :+1:
