### ISSUE TITLE
parse error on links

### ISSUE THREAD

**Issue by SimonLab** [akitten/public-profile-page-url-finder#4]
![linkedinerror](https://cloud.githubusercontent.com/assets/6057298/10226367/dd96c2a2-685e-11e5-8e6f-57f565a80eea.png)
https://github.com/nelsonic/public-profile-page-url-finder/blob/master/lib/finder.js#L21
The link is sometimes formatted by the search engine and will raise an error when parsing.
Is parsing the href of the result title a better choice?

**Comment by nelsonic** [comment]
closed by #5
