### ISSUE TITLE
return only public profile urls

### ISSUE THREAD

**Issue by heron2014** [akitten/public-profile-page-url-finder#6]
only take public profile urls
![links](https://cloud.githubusercontent.com/assets/8476884/10244088/e7ecc44a-68f4-11e5-8a71-610dc3403892.png)

**Comment by nelsonic** [comment]
@heron2014 agree. for now, we want to *ignore* `/pub/` urls. :+1: 
Do you have time to write that test and update the code?

**Comment by heron2014** [comment]
@nelsonic yes, that's the plan! :)

**Comment by nelsonic** [comment]
Pub URLs are no longer an issue. se have https://github.com/akitten/linkedin-canonical-url to resolve them.
