### ISSUE TITLE
Parsing error when the link is a document

### ISSUE THREAD

**Issue by SimonLab** [akitten/public-profile-page-url-finder#9]
When the links refer to a document (pdf for example), the finder select the wrong tag: https://github.com/akitten/public-profile-page-url-finder/blob/master/lib/finder.js#L24
It needs to select the child with a tag 'a' instead of the span
![wrongchild](https://cloud.githubusercontent.com/assets/6057298/10280994/590fa84c-6b69-11e5-87ea-fa5929642abf.png)

**Comment by nelsonic** [comment]
Please write a test for this condition and add an if statement. Let me know if you need help.
Or... simply give me the link to the search where you are seeing this issue and I will write it.
Thanks.

**Comment by SimonLab** [comment]
I was searching with Abdi profile: https://www.google.co.uk/search?q=Abdi+Ahmed+Founders+and+Coders&oq=abdi+&aqs=chrome.0.69i59j69i57j69i59j0l3.1762j0j7&sourceid=chrome&es_sm=93&ie=UTF-8

**Comment by SimonLab** [comment]
A simple solution might just be to add a OR condition 
```
titleLinks[i].children[0].attribs.href || titleLinks[i].children[1].attribs.href;
```
But I don't know if a titleLinks can have more than 2 childrens

**Comment by nelsonic** [comment]
Simon fixe this in #11
